"use client";
import { Home } from "@/containers/Home/Home";
import Head from "next/head";

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Microwall App</title>
        <meta
          name="description"
          content="Task Assignment App Generated By Next"
        />
      </Head>
      <Home />
    </>
  );
}
